###get songs
GET http://localhost:3000/api/songs

###create new song in album
POST http://localhost:3000/api/album/12/songs
Content-Type: application/json

{

}

###get songs by album id
GET http://localhost:3000/api/album/1/songs

###get user liked songs
GET http://localhost:3000/api/user/4cf5ea9f-0111-47ff-974c-0d4e6d716e08/songs
