### Este archivo contiene los endpoints iniciales para poder comenzar a usar la api

### Te debes de registrar para poder tener tu cuenta y poder iniciar sesion
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "username":"anonimo",
    "email":"anonimo@gmail.com",
    "password":"Test123!"
}

### Debes de iniciar sesion para poder utilizar los demas endpoints ya que requeriras un token
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email":"anonimo@gmail.com",
    "password":"Test123!"
}

### Crear un artista es necesario para despues crear un album
POST http://localhost:3000/api/artists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxOWYxYzEwLWM1ZWQtNDkyMS05MmZlLTc5ZTM4NGJlMDI3OCIsImVtYWlsIjoiYWJlbEBnbWFpbC5jb20iLCJpYXQiOjE2OTkyODA4MDV9.v-365CZyEG5_ImP5HlrnVIQnLUdu9AOpLAs2n1FZIBA

{
    "name":"Gorillaz",
    "nationality":"American"
}

### Crear un album al que despues le podras agregar canciones
POST http://localhost:3000/api/artists/9/albums
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxOWYxYzEwLWM1ZWQtNDkyMS05MmZlLTc5ZTM4NGJlMDI3OCIsImVtYWlsIjoiYWJlbEBnbWFpbC5jb20iLCJpYXQiOjE2OTkyODA4MDV9.v-365CZyEG5_ImP5HlrnVIQnLUdu9AOpLAs2n1FZIBA

{
    "name":"Cracker Island",
    "release_date":"2018-04-27T00:00:00Z"
}

### Agregar una cancion a un album en especifico
POST http://localhost:3000/api/albums/1/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUxOWYxYzEwLWM1ZWQtNDkyMS05MmZlLTc5ZTM4NGJlMDI3OCIsImVtYWlsIjoiYWJlbEBnbWFpbC5jb20iLCJpYXQiOjE2OTkyODA4MDV9.v-365CZyEG5_ImP5HlrnVIQnLUdu9AOpLAs2n1FZIBA

{
    "name":"Over Now",
    "duration":"4:07"
}

### Con estos endpoints ya puedes empezar a manejar los datos a tu gusto
